# Generated by Django 3.2.7 on 2021-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(default=0)),
                ('label_list', models.JSONField()),
                ('image', models.TextField(default='')),
                ('read_count', models.IntegerField(default=0)),
            ],
        ),
    ]
